name: Compile JOSS paper

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Compile paper
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build JOSS paper
        uses: openjournals/openjournals-draft-action@v1
        with:
          journal: joss
          paper-path: paper/paper.md
